import {mountTurningSimulation} from './simulation.js?v=0.3.0';
let simulation=null;
import {calculate,convertSpeed} from './math.js?v=0.3.0';
const $=s=>document.querySelector(s), titles={turning:'Точение',milling:'Фрезерование',drilling:'Сверление',threading:'Резьба'}, descriptions={turning:'Наружное и внутреннее точение',milling:'Торцевое и концевое фрезерование',drilling:'Сверление и рассверливание',threading:'Нарезание резьбы'};
const icons={verified:'<path d="M9 3h6l1 3h4v15H4V6h4zM8 13l3 3 5-6"/>',home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3z"/>',calc:'<rect x="5" y="2" width="14" height="20" rx="3"/><path d="M8 6h8M8 11h1m6 0h1M8 15h1m6 0h1M8 19h1m6 0h1"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7m2-5v6l4 3"/>',settings:'<path d="m10 3 4 0 1 3 3 1 3 3-2 3 0 3-3 2-3-1-3 1-3-2 0-3-2-3 3-3 3-1z"/><circle cx="12" cy="12" r="3"/>'};
let verified;try{verified=JSON.parse(localStorage.getItem('verified-modes')||'[]');if(!Array.isArray(verified))verified=[]}catch{verified=[]}let savingVerified=false;
let current='home',material=localStorage.getItem('material')||'AISI 304',history;try{history=JSON.parse(localStorage.getItem('history')||'[]');if(!Array.isArray(history))history=[]}catch{history=[]}
let theme=localStorage.getItem('theme')||'dark';function setTheme(){document.body.classList.toggle('light',theme==='light');$('#theme').textContent=theme==='light'?'☾':'☀';localStorage.setItem('theme',theme)}setTheme();$('#theme').onclick=()=>{theme=theme==='dark'?'light':'dark';setTheme()};
function dock(active){$('.dock').innerHTML=[['home','Главная'],['calc','Расчёты'],['history','История'],['verified','Проверенные режимы'],['settings','Настройки']].map(([id,t])=>`<button data-nav="${id}" class="${id===active?'active':''}" ${id===active?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true">${icons[id]}</svg>${t}</button>`).join('');$('.dock').querySelectorAll('button').forEach(b=>b.onclick=()=>render(b.dataset.nav))}
function materialRow(){return `<div class="row glass"><span class="metal" aria-hidden="true"></span><div style="flex:1"><label for="material"><small>Материал заготовки</small></label><select id="material">${['AISI 304','Сталь','Полиамид','Латунь'].map(m=>`<option ${m===material?'selected':''}>${m}</option>`).join('')}</select></div></div>`}
function render(page){if(simulation){simulation.dispose();simulation=null}savingVerified=false;current=page;dock(page in titles?'calc':page);const v=$('#view');if(page==='home'||page==='calc'){v.innerHTML=`${page==='calc'?'<div class="section-title"><h2>Выберите операцию</h2></div>':''}<div class="grid">${Object.entries(titles).map(([id,t])=>`<button class="card" data-mode="${id}"><span class="art ${id}"></span><span class="card-copy"><h2>${t}</h2><p>${descriptions[id]}</p><span class="arrow">›</span></span></button>`).join('')}</div>${materialRow()}<button class="row glass" id="last"><svg viewBox="0 0 24 24">${icons.history}</svg><div><small>Последний расчёт</small><strong>${history.length?titles[history[0].mode]+' · '+Math.round(history[0].n)+' об/мин':'История расчётов'}</strong></div></button>`;v.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>render(b.dataset.mode));$('#last').onclick=()=>render('history')}
else if(page in titles){renderOperation(page)}
else if(page==='verified'){v.innerHTML=`<div class="section-title"><h2>Проверенные режимы</h2></div><p class="hint">Твои режимы, проверенные в работе. Хранятся на этом устройстве.</p><div class="glass row"><div style="width:100%"><label for="operation">Операция</label><select id="operation">${Object.entries(titles).map(([k,t])=>`<option value="${k}">${t}</option>`).join('')}</select><button class="primary" id="add-mode">Добавить проверенный режим</button></div></div>${verified.length?verified.map(h=>`<article class="glass history-entry"><h3>${titles[h.mode]} · ${h.material}</h3><p>D ${h.d} мм · S ${Math.round(h.n)} об/мин · V ${h.vc.toFixed(1)} м/мин</p>${h.ap?`<p>ap ${h.ap} мм на сторону</p>`:''}<p>${h.mode==='threading'?'P '+h.pitch+' мм':(h.mode==='milling'?'fz ':'F ')+h.f+(h.mode==='milling'?' мм/зуб · z '+h.z:' мм/об')}</p></article>`).join(''):'<div class="glass empty" style="margin-top:16px">Пока нет сохранённых режимов.</div>'}`;$('#add-mode').onclick=()=>{savingVerified=true;renderOperation($('#operation').value);dock('verified')}}
else if(page==='history'){v.innerHTML=`<div class="section-title"><h2>История расчётов</h2></div>${history.length?history.map((h,i)=>`<article class="glass history-entry"><small>${new Date(h.date).toLocaleString('ru-RU')}</small><h3>${titles[h.mode]} · ${h.material}</h3><p>D ${h.d} мм · Vc ${h.vc} м/мин</p><strong>${Math.round(h.n)} об/мин · ${h.feed.toFixed(1)} мм/мин</strong><br><button class="text-button" data-copy="${i}">Копировать результат</button></article>`).join('')+'<button class="text-button" id="clear">Очистить историю</button>':'<div class="glass empty">Здесь появятся сохранённые расчёты.</div>'}`;v.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const h=history[Number(b.dataset.copy)];try{await navigator.clipboard.writeText(`${titles[h.mode]} · ${h.material}\nD ${h.d} мм · Vc ${h.vc} м/мин\nn ${Math.round(h.n)} об/мин · Vf ${h.feed.toFixed(1)} мм/мин`);toast('Скопировано')}catch{toast('Браузер не разрешил копирование')}});if($('#clear'))$('#clear').onclick=()=>{if(confirm('Удалить историю расчётов?')){history=[];localStorage.removeItem('history');render('history')}}}
else{v.innerHTML='<div class="section-title"><h2>Настройки</h2></div><button id="switch" class="row glass">Переключить светлую / тёмную тему</button><div class="glass row"><div><strong>Calculator Pro 2026</strong><p>Личные расчёты хранятся на этом устройстве. После первой загрузки приложение работает без интернета.</p><p>На iPhone: меню «Поделиться» → «На экран Домой».</p><small>Версия 0.3.0 · интерактивная основа</small></div></div>';$('#switch').onclick=()=>$('#theme').click()}
if($('#material'))$('#material').onchange=e=>{material=e.target.value;localStorage.setItem('material',material)};window.scrollTo({top:0,behavior:'instant'})}
function renderOperation(mode){
if(simulation){simulation.dispose();simulation=null}
let speedMode='s';const speedField=()=>[speedMode==='s'?'s':'vc',speedMode==='s'?'S':'V',speedMode==='s'?'Обороты шпинделя':'Скорость резания',speedMode==='s'?'об/мин':'м/мин'];
const extra=mode==='threading'?[['pitch','P','Шаг резьбы','мм']]:[['f',mode==='milling'?'fz':'F',mode==='milling'?'Подача на зуб':'Подача на оборот',mode==='milling'?'мм/зуб':'мм/об']];if(mode==='milling')extra.push(['z','z','Число зубьев','шт']);
if(mode==='turning')extra.push(['ap','ap','Глубина на сторону','мм'],['l','L','Длина прохода','мм']);
const base=[['d','D',mode==='milling'||mode==='drilling'?'Диаметр инструмента':'Диаметр обработки','мм'],...extra];
const row=([id,symbol,label,unit])=>`<div class="parameter-row"><strong class="symbol">${symbol}</strong><label for="${id}">${label}</label><input id="${id}" name="${id}" type="number" inputmode="decimal" step="${id==='z'?'1':'any'}" min="${id==='z'?'1':'0.000001'}" ${id==='ap'||id==='l'?'':'required'} value="" aria-label="${label}"><span class="unit">${unit}</span></div>`;
$('#view').innerHTML=`<div class="calculator"><div class="section-title"><button class="back" id="back" aria-label="Назад">‹</button><div><h2>${titles[mode]}</h2><small class="hint">${savingVerified?'Проверенный режим':'Параметры обработки'}</small></div></div><div class="hero"><span class="art ${mode}"></span></div>${materialRow()}<form id="form"><div class="speed-toggle glass" role="group" aria-label="Способ задания скорости"><button type="button" id="speed-s" class="selected" aria-pressed="true">S · об/мин</button><button type="button" id="speed-v" aria-pressed="false">V · м/мин</button></div><div class="parameter-table glass">${base.map(row).join('')}<div id="speed-row">${row(speedField())}</div></div>${mode==='turning'?'<div id="simulation"></div>':''}<div id="error" class="error" role="alert"></div><div id="results" class="results" aria-live="polite"><p class="hint">Введите параметры для расчёта</p></div><button class="primary" type="submit">${savingVerified?'Сохранить режим':'Рассчитать и сохранить'}</button></form>${mode==='turning'?'<p class="hint">ap — глубина на сторону при наружном продольном точении. Съём 1 мм на сторону уменьшает диаметр на 2 мм. Поле необязательное.</p>':''}<p class="hint">Обозначения как на стойке. Результат — пересчёт твоих значений, а не назначение режимов.</p></div>`;
$('#material').onchange=e=>{material=e.target.value;localStorage.setItem('material',material)};$('#back').onclick=()=>render(savingVerified?'verified':'home');const clear=()=>{if(simulation)simulation.reset();$('#results').innerHTML='<p class="hint">Введите параметры для расчёта</p>';$('#error').textContent=''};$('#form').addEventListener('input',clear);
function switchSpeed(next){if(next===speedMode)return;const old=speedMode,oldInput=$('#'+(old==='s'?'s':'vc')),value=Number(oldInput.value),d=Number($('#d').value);let converted='';if(oldInput.value!==''&&d>0&&value>0)converted=String(Number(convertSpeed(d,value,old).toPrecision(12)));speedMode=next;$('#speed-row').innerHTML=row(speedField());$('#'+(next==='s'?'s':'vc')).value=converted;for(const [id,m]of [['speed-s','s'],['speed-v','v']]){$('#'+id).classList.toggle('selected',m===next);$('#'+id).setAttribute('aria-pressed',String(m===next))}clear();if(value>0&&!(d>0))$('#error').textContent='Для пересчёта скорости сначала введи диаметр.'}
if(mode==='turning')simulation=mountTurningSimulation($('#simulation'),()=>{try{const d=Number($('#d').value),ap=Number($('#ap').value),l=Number($('#l').value),f=Number($('#f').value);const p={d,f,speedMode};p[speedMode==='s'?'s':'vc']=Number($('#'+(speedMode==='s'?'s':'vc')).value);return {d,ap,l,feed:calculate(mode,p).feed}}catch{return null}});
$('#speed-s').onclick=()=>switchSpeed('s');$('#speed-v').onclick=()=>switchSpeed('v');
$('#form').onsubmit=e=>{e.preventDefault();try{const keys=[...base.map(x=>x[0]),speedMode==='s'?'s':'vc'];const p=Object.fromEntries(keys.filter(k=>!['ap','l'].includes(k)||$('#'+k).value!=='').map(k=>[k,Number($('#'+k).value)]));p.speedMode=speedMode;if(mode==='turning'&&p.ap&&2*p.ap>=p.d)throw Error('Глубина должна быть меньше половины диаметра.');const r=calculate(mode,p);$('#error').textContent='';$('#results').innerHTML=`<div class="readouts"><div class="glass readout"><small>${speedMode==='s'?'V · Скорость резания':'S · Обороты шпинделя'}</small><strong>${speedMode==='s'?r.vc.toFixed(1):Math.round(r.n)} <span>${speedMode==='s'?'м/мин':'об/мин'}</span></strong></div><div class="glass readout"><small>Минутная подача</small><strong>${r.feed.toFixed(1)} <span>мм/мин</span></strong></div></div>`;if(mode==='turning'&&p.ap){const finalD=p.d-2*p.ap;const q=Math.PI*(p.d*p.ap-p.ap*p.ap)*r.feed/1000;$('#results').insertAdjacentHTML('beforeend',`<div class="glass depth-results"><p>После прохода: Ø <strong>${Number(finalD.toFixed(3))} мм</strong></p><p>Уменьшение диаметра: <strong>${Number((2*p.ap).toFixed(3))} мм</strong></p><p>Объём съёма: <strong>${q.toFixed(2)} см³/мин</strong></p><small>Для наружного продольного точения при постоянном диаметре. Допустимая нагрузка зависит от инструмента и закрепления.</small></div>`)}if(savingVerified){verified.unshift({mode,material,...p,...r,date:new Date().toISOString()});localStorage.setItem('verified-modes',JSON.stringify(verified));render('verified');toast('Проверенный режим сохранён');return}history.unshift({mode,material,...p,...r,date:new Date().toISOString()});history=history.slice(0,100);localStorage.setItem('history',JSON.stringify(history));toast('Расчёт сохранён')}catch(e){$('#error').textContent=e.message}};
}
let timer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}render('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(()=>{$('#connection').textContent='Офлайн-оболочка подключена · данные на устройстве'}).catch(()=>{$('#connection').textContent='Офлайн пока недоступен · открой по HTTPS'});
